cutting down on the debugging
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/pkgs@14135 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/untangle-net-alpaca/files/etc/untangle-net-alpaca/scripts/modules b/untangle-net-alpaca/files/etc/untangle-net-alpaca/scripts/modules
--- a/untangle-net-alpaca/files/etc/untangle-net-alpaca/scripts/modules
+++ b/untangle-net-alpaca/files/etc/untangle-net-alpaca/scripts/modules
@@ -16,11 +16,7 @@ MODULES="nf_conntrack \
 
 for module in $MODULES ; do 
     modprobe $module
-    if [ "$?" -gt 0 ]; then
-        echo "ERROR loading module $module"
-    else
-        echo "$module loaded successfully."
-    fi
+    if [ "$?" -gt 0 ]; then echo "ERROR loading module $module";  fi
 done
 
 exit 0
