Closes: #5544 Use hostname without -f to get the correct cert Compile for java5 since we'll use java5 at upgrade time due to PATH migration script now -e, pem removed on failure
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/branch/prod/release-6.0/work/pkgs@20735 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/untangle-apache2-config/debian/untangle-apache2-config.postinst b/untangle-apache2-config/debian/untangle-apache2-config.postinst
--- a/untangle-apache2-config/debian/untangle-apache2-config.postinst
+++ b/untangle-apache2-config/debian/untangle-apache2-config.postinst
@@ -5,7 +5,7 @@ exec > /tmp/untangle-apache2-config.log 2>&1
 
 KEYSTORE=/usr/share/untangle/conf/keystore
 PEM=/etc/apache2/ssl/apache.pem
-ALIAS=$(hostname -f)
+ALIAS=$(hostname)
 
 if [ -z "$ALIAS" ] || [ "$ALIAS" = "Knoppix.metaloft.com" ] ; then
     echo setting ALIAS to default value
@@ -54,6 +54,10 @@ fi
 if [ ! -e $PEM -a -e $KEYSTORE ]; then
     echo 'moving cert from java keystore'
     /usr/share/untangle-apache2-config/keystore2pem.sh $KEYSTORE $PEM $ALIAS
+    if [ $? -ne 0 ]; then
+    	echo "failed, removing"
+	rm $PEM
+    fi
 fi
 
 if [ ! -e $PEM ]; then
