Change AWS to set initial password to instance ID. Remove internal interface from default settings. Require password on setup wizard.

diff --git a/untangle-hardware-amazon-ec2/debian/untangle-hardware-amazon-ec2.postinst b/untangle-hardware-amazon-ec2/debian/untangle-hardware-amazon-ec2.postinst
--- a/untangle-hardware-amazon-ec2/debian/untangle-hardware-amazon-ec2.postinst
+++ b/untangle-hardware-amazon-ec2/debian/untangle-hardware-amazon-ec2.postinst
@@ -14,5 +14,27 @@ rm -f /usr/share/untangle-snort-config/current/rules/emerging-deleted.rules
 rm -f /usr/share/untangle-snort-config/current/rules/emerging-current_events.rules
 rm -f /usr/share/untangle-snort-config/current/rules/emerging-activex.rules
 
+# Make specific wizard settings for AWS
+# For AWS the password is required to get to the setup wizard the first time
+mkdir -p /usr/share/untangle/conf
+cat > /usr/share/untangle/conf/wizard.js <<EOF
+{
+    "javaClass": "com.untangle.uvm.WizardSettings",
+    "wizardComplete": false,
+    "passwordRequired": true,
+}
+EOF
+
+# Set the initial admin password to the instance ID
+PASS="`curl -s -q -m 5 http://169.254.169.254/latest/meta-data/instance-id`"
+if [ $? != 0 ] ; then
+    echo -e "\n\nWARNING\n\nFailed to retrieve instance ID\n\n"
+elif [ "$PASS" == "" ] ; then
+    echo -e "\n\nWARNING\n\nInvalid instance ID value\n\n"
+else
+     /usr/share/untangle/bin/ut-set-admin-passwd.py $PASS
+fi
+
 exit 0
 
+ut-set-admin-passwd.py
