if module fails to load run depmod

diff --git a/untangle-hardware-linksys-wrt1900acs/files/etc/untangle/hardware/firmware.d/22wifi b/untangle-hardware-linksys-wrt1900acs/files/etc/untangle/hardware/firmware.d/22wifi
--- a/untangle-hardware-linksys-wrt1900acs/files/etc/untangle/hardware/firmware.d/22wifi
+++ b/untangle-hardware-linksys-wrt1900acs/files/etc/untangle/hardware/firmware.d/22wifi
@@ -1,9 +1,13 @@
 #! /bin/sh
 
+# if loading compat fails, run depmod
+modprobe compat
+if [ ! $? -eq 0 ] ; then
+    depmod -a
+fi
+
 # if any command fails after this, exit with error
 set -e
-
-depmod -a -A
 
 # load modules
 modprobe compat
