NGFW-15528 geoip download retry and md5 sum validation

diff --git a/untangle-geoip-database/files/etc/cron.daily/geoip-update b/untangle-geoip-database/files/etc/cron.daily/geoip-update
--- a/untangle-geoip-database/files/etc/cron.daily/geoip-update
+++ b/untangle-geoip-database/files/etc/cron.daily/geoip-update
@@ -1,4 +1,5 @@
 #!/bin/sh
+exec &> >(logger -t uvmreports)
 #
 # This file is part of the untangle-geoip-database package.  We hook into
 # the monthly cron process to download a new database file for the
@@ -18,11 +19,14 @@ TEMPFILE=/tmp/geoip-download.tar.gz
 # This is the name of the update file the Uvm will watch for
 UPFILE=/var/cache/untangle-geoip/GeoLite2-Country.update
 
+# This is the current GeoIP database file
+DBFILE=/usr/share/untangle/geoip/GeoLite2-Country.mmdb
+
 # This is the path where we extract the update tarball
-COUNTRYPATH=/tmp/geoip-update
+TARBALLPATH=/tmp/geoip-update
 
 # This is the full path to the database file extracted from the update tarball
-COUNTRYFILE=/tmp/geoip-update/GeoLite2-Country.mmdb
+TEMPDBFILE="$TARBALLPATH/GeoLite2-Country.mmdb"
 
 # Get the UID so we can pass it in the download request
 UID=`cat /usr/share/untangle/conf/uid`
@@ -37,8 +41,8 @@ if [ -f $TEMPFILE ]; then
 fi
 
 # Remove any existing extraction directory that may have been created
-if [ -d $COUNTRYPATH ]; then
-    /bin/rm -r -f $COUNTRYPATH
+if [ -d $TARBALLPATH ]; then
+    /bin/rm -r -f $TARBALLPATH
     if [ $? -ne 0 ]; then
 	printf "Unable to remove existing GeoIP extraction directory\n"
 	exit 1
@@ -46,12 +50,17 @@ if [ -d $COUNTRYPATH ]; then
 fi
 
 # Download the update from the external server
-/usr/bin/wget -O $TEMPFILE $NETURL?resource=geoipCountry&uid=$UID
-wait
-if [ $? -ne 0 ]; then
-    printf "Unable to download new GeoIP database\n"
-    exit 1
-fi
+for i in 1 2 3; do
+    /usr/bin/wget -O $TEMPFILE $NETURL?resource=geoipCountry&uid=$UID
+    if [ $? -eq 0 ]; then
+        break
+    fi
+    if [ $i -eq 3 ]; then
+        printf "Unable to download new GeoIP database\n"
+        exit 1
+    fi
+    sleep 5
+done
 
 # Make sure we actually received the file
 if [ ! -f $TEMPFILE ]; then
@@ -60,14 +69,14 @@ if [ ! -f $TEMPFILE ]; then
 fi
 
 # Create a directory where we can extract the update files
-/bin/mkdir $COUNTRYPATH
-if [ ! -d $COUNTRYPATH ]; then
+/bin/mkdir $TARBALLPATH
+if [ ! -d $TARBALLPATH ]; then
     printf "Unable to create temporary update directory\n"
     exit 1
 fi
 
 # Extract the files from the tarball to a temporary directory
-/bin/tar xvfz $TEMPFILE --directory $COUNTRYPATH --strip=1
+/bin/tar xvfz $TEMPFILE --directory $TARBALLPATH --strip=1
 wait
 if [ $? -ne 0 ]; then
     printf "Unable to extract GeoIP update file\n"
@@ -75,9 +84,21 @@ if [ $? -ne 0 ]; then
 fi
 
 # Make sure the update database file isn't empty
-if [ ! -s $COUNTRYFILE ]; then
+if [ ! -s $TEMPDBFILE ]; then
     printf "The extracted GeoIP database file is empty\n"
     exit 1
+fi
+
+# If the md5 sums are the same, then we don't need to do anything
+if [ -f $DBFILE ]; then
+    NEWSUM=`md5sum $TEMPDBFILE | awk '{print $1}'`
+    OLDSUM=`md5sum $DBFILE | awk '{print $1}'`
+    if [ "$NEWSUM" = "$OLDSUM" ]; then
+        # Remove the downloaded file and extraction directory
+        /bin/rm -f $TEMPFILE
+        /bin/rm -r -f $TARBALLPATH
+        exit 0
+    fi
 fi
 
 # Remove any existing update file
@@ -90,10 +111,10 @@ if [ -f $UPFILE ]; then
 fi
 
 # Copy the update file to where the Uvm will look for it
-/bin/cp $COUNTRYFILE $UPFILE
+/bin/cp $TEMPDBFILE $UPFILE
 
 # Remove the downloaded file and extraction directory
 /bin/rm -f $TEMPFILE
-/bin/rm -r -f $COUNTRYFILE
+/bin/rm -r -f $TEMPDBFILE
 
 exit 0
