fix handling of quotes for comments in iptables
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/pkgs@32962 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/untangle-net-alpaca/files/usr/share/untangle-net-alpaca/scripts/generate-iptables-rules b/untangle-net-alpaca/files/usr/share/untangle-net-alpaca/scripts/generate-iptables-rules
--- a/untangle-net-alpaca/files/usr/share/untangle-net-alpaca/scripts/generate-iptables-rules
+++ b/untangle-net-alpaca/files/usr/share/untangle-net-alpaca/scripts/generate-iptables-rules
@@ -21,15 +21,15 @@ LOCK_FILE=/tmp/generate-iptables-rules.lock
 
 iptables_debug()
 {
-   echo "[`date`] /sbin/iptables $*"
-   /sbin/iptables $*
+   echo "[`date`] /sbin/iptables $@"
+   /sbin/iptables "$@"
 }
 
 iptables_debug_onerror()
 {
     # Ignore -N errors
-    /sbin/iptables $* || {
-        [ "${3}x" != "-Nx" ] && echo "[`date`] Failed: /sbin/iptables $*"
+    /sbin/iptables "$@" || {
+        [ "${3}x" != "-Nx" ] && echo "[`date`] Failed: /sbin/iptables $@"
     }
 
     true
@@ -38,8 +38,8 @@ iptables_debug_onerror()
 
 ebtables_debug()
 {
-    echo "[`date`] /sbin/ebtables $*"
-    /sbin/ebtables $*
+    echo "[`date`] /sbin/ebtables $@"
+    /sbin/ebtables "$@"
 }
 
 get_ip_addresses()
